using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using Taxlab.ApiClientLibrary;

namespace Taxlab.ApiClientCli.Implementations
{
    public static class TestSetup
    {
        private static readonly HttpClient HttpClient = new HttpClient();

        //choose api location
        private static readonly string BaseUrl = "https://localhost:44359/";
        //private static readonly string BaseUrl = "https://preview.taxlab.online/api-internal/";

        //add B2C token or jwtToken based on scenario
        private static readonly string Token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ilg1ZVhrNHh5b2pORnVtMWtsMll0djhkbE5QNC1jNTdkTzZRR1RWQndhTmsifQ.eyJleHAiOjE2Nzc3MjU0MTMsIm5iZiI6MTY3NzcyMTgxMywidmVyIjoiMS4wIiwiaXNzIjoiaHR0cHM6Ly90YXhsYWJwdWJsaWMuYjJjbG9naW4uY29tL2I3MmMzZmY4LTM2NjEtNDRhYi05ZGYzLWU2YjM4NWI1ZTc2Zi92Mi4wLyIsInN1YiI6IjNkNjY1ZWE5LWY2NjYtNDM1Ny1iN2UyLTJhZjUyYzg3ZjA1MCIsImF1ZCI6ImYyYTNlYjU1LWE1ODAtNGE1My04NTc0LThlZTYyZTk0ZDMzNyIsIm5vbmNlIjoiNjM4MTMzMTg2MDM2MDg2NDI5LllqUmtNVFJtT0RjdFlqVXpOeTAwTVRjeExXRm1aakF0T1RrMFpESTBaRFEyTldZMllqTm1aRGRpTjJFdFlXRmtNeTAwTVdJMUxXRTVNV1l0WXpjNU4yRTFZalppTldFMSIsImlhdCI6MTY3NzcyMTgxMywiYXV0aF90aW1lIjoxNjc3NzIxODEwLCJpZHBfYWNjZXNzX3Rva2VuIjoiUEFRQUJBQUFBQUFELS1ETEEzVk83UXJkZGdKZzdXZXZyTTd1Zk1HSVM3S1RJRlk5QklfS0RfZ0dGczQ2NWZzQVp1WWdScGhIV0JDWmVvcjREbUNSMFJSVjFWeHdkWnhQU0lHUnFiU2dSZG4xUXdSN2h5UHlJMFg0T1JreUpXWTFpQTh5U1c0dDlWa0NudFc0UkFuRTBLekhhejdvSVM2all3MDVDZlJZOXVrX210dVFNWmRycElZZmt5RC13WFJqLVJUQUJMaldnYTZzUkE5UHZfTk5EcVpwdWRKMXFsRVB4VlhEU3Q4ODVNQkI0V3pKMWE5eXc5RWg5bWJ2QmFUYm9CX1A1WWNSenh2b2xVTDhWTUJYUFNyVW4xeTlBcGRucjU5LWcwZnZUUF95aWJQb0p4ZkY0NVF2bFgyUTFWa19POGtpNFV5YjAtRjgwd3JmakgwS253Uk1wbS1tNV9EV0w1Q0VSQTBacjdDM2pnemhIaHhRdmhlS2lYWmJkVEItcGw5WVZkc2FCejFoZkJGcWpUamk3T1BLaWdhWTBxakJFZWNOaUJxMUpMMHVhYklCSW9fVmxxV2JHOHF6LUhnMEZKTE9nd1NlLXctWXBMXzVqQjhMQjVwSERxZUlXNC1TY1NFQXcxZnZpYTJ3MDJkS180WGhRY2xLaURZYWJZRGdaQm5Ra2tMTTFrSGoySnl2WGMteXRqOHgzdG4weFVXako4VE9uZ2hTVXJVZ3YzNHJfYko2cWFXT0RVOFBySmZJSUhocWJSWWIwZmRyakJYZ1VsWWRBWHlxdjFENEFNSnZxRkVscGtDendRb1p4YnlCZjV3TVpfUG8tRnBnUXZDVEZZcEVrRFF3YTNIWkk3SWtwRjJjcWRPb2FqT2x4Y2JWeHlwWUo5MUZuTlpfcjRGTnFwZG42V29UUkNZSzBkeEdBUTlkSzZoWlRFa2dJdW91eTQ2U0tnaTRwaUZ4bWRhSWZCUnRYdFp3OWFmMDR2bkRuNHJ6QnVxUTVRTU5MNzRyS2Nva3hiNnR0dVlldUlBeHZyUXVEUFdDTHVfQnR4RkNBbGR0Q2xleDJNN0EtYThkV0RxTmdyU0FBIiwiaWRwIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvZThhMjZiZTYtMmEzZC00MTQ0LThlMzctZTIxNmUyMmZhMWRlLyIsImdpdmVuX25hbWUiOiJEYW5lc2giLCJmYW1pbHlfbmFtZSI6IkJhbGFzaW5nYW0iLCJuYW1lIjoiRGFuZXNoIEJhbGFzaW5nYW0iLCJvaWQiOiIzZDY2NWVhOS1mNjY2LTQzNTctYjdlMi0yYWY1MmM4N2YwNTAiLCJleHRlbnNpb25fdGVybXNPZlVzZSI6dHJ1ZSwiZW1haWxzIjpbImRhbmVzaC5iYWxhc2luZ2FtQHRheGxhYi5vbmxpbmUiXSwidGZwIjoiQjJDXzFfTG9jYWxTaWdudXBXaXRoTWZhVE9UUCJ9.N6FhyCw05y-cZFr47nsk76gnaLy4LFhqunySaBnT4nx6NcoMe6bEYt3cupIxU49XtQFbIMP84gUWvYYxxzHeKvfmjNG2oZ_lX6fNclp2XLz0QyezuJwSq-DFl-1s8jXaixQRm1UPVS-2-cxWOs3UURofSaeg59s3BU4kt8bMrXFGn4tkjnQTuR52euMNr0g-6JcKGSYtfZ0kTbOTxoOsBKCIGovZFbUHda8CmeyU2O7TdCFP1PzSd4ZWIjANMwcJ-EUoHILEHSvDX_OYd8107VM1u8jgvUiHhibDP91H7BWBAhuEs9wxFM1G_aUXe2wtkcZlM3SOqr2QI4Bc4x4PLQ";

        public static TaxlabApiClient GetTaxlabApiClient()
        {
            var authService = new AuthService(Token);
            return new TaxlabApiClient(BaseUrl, HttpClient, authService);

        }
    }
}
